# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            felixfoertsch.de
tagline:          'Rocketing along. ðŸš€'
version:          11
description:      ''
url:              https://felixfoertsch.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Felix FÃ¶rtsch'
  url:            felixfoertsch.de
  flair:          ''

paginate:         10
paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-octicons
  - jekyll-github-metadata

include:
  - keybase.txt

exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-hydeout.gemspec
  - LICENSE.md
  - Makefile
  - package.json
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Sidebar link settings
sidebar_home_link:  true

github:
  profile: 'https://github.com/felixfoertsch'
twitter:
  profile: 'https://twitter.com/felixfoertsch'